<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-28T11:35:38 IST" name="Suite" finished-at="2025-10-28T11:36:06 IST" duration-ms="28314">
    <groups>
      <group name="smoke">
        <method signature="LoginTest.logintest()[pri:0, instance:com.ecom.testcases.LoginTest@349c1daf]" name="logintest" class="com.ecom.testcases.LoginTest"/>
        <method signature="RegistrationTest.registrationtest()[pri:0, instance:com.ecom.testcases.RegistrationTest@23d1e5d0]" name="registrationtest" class="com.ecom.testcases.RegistrationTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2025-10-28T11:35:38 IST" name="parallelTest" finished-at="2025-10-28T11:36:06 IST" duration-ms="28314">
      <class name="com.ecom.testcases.RegistrationTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.ecom.testcases.RegistrationTest@23d1e5d0]" started-at="2025-10-28T11:35:38 IST" name="setup" finished-at="2025-10-28T11:35:49 IST" duration-ms="10995" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="registrationtest()[pri:0, instance:com.ecom.testcases.RegistrationTest@23d1e5d0]" started-at="2025-10-28T11:35:49 IST" name="registrationtest" finished-at="2025-10-28T11:36:05 IST" duration-ms="15724" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.ecom.testcases.RegistrationTest.registrationtest(RegistrationTest.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registrationtest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.ecom.testcases.RegistrationTest@23d1e5d0]" started-at="2025-10-28T11:36:05 IST" name="teardown" finished-at="2025-10-28T11:36:06 IST" duration-ms="798" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.ecom.testcases.RegistrationTest -->
      <class name="com.ecom.testcases.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.ecom.testcases.LoginTest@349c1daf]" started-at="2025-10-28T11:35:38 IST" name="setup" finished-at="2025-10-28T11:35:48 IST" duration-ms="9603" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="logintest()[pri:0, instance:com.ecom.testcases.LoginTest@349c1daf]" started-at="2025-10-28T11:35:49 IST" name="logintest" finished-at="2025-10-28T11:36:03 IST" duration-ms="14524" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.ecom.testcases.LoginTest.logintest(LoginTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.ecom.testcases.LoginTest@349c1daf]" started-at="2025-10-28T11:36:04 IST" name="teardown" finished-at="2025-10-28T11:36:04 IST" duration-ms="273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.ecom.testcases.LoginTest -->
    </test> <!-- parallelTest -->
  </suite> <!-- Suite -->
</testng-results>
